### PR TITLE
add simple e2e testcase 

### PR DESCRIPTION
**Pull request by cdlliuy**
:broom:  as title, as simple e2e testcases

### CODE REVIEW

**Review by maximilien — DISMISSED** [review]
thanks for updating this. I will merge it. We will need more tests for this should work well to start with. Thanks @cdlliuy 
/ok-to-test
/approve
/lgtm

**Comment by maximilien** [comment]
Seems like your e2e test is still failing... 

```bash
 Missing strings: revision, spec.replicas
uninstalling 'kn' plugin 'kn-diag' from config path '/root/.config/kn'
    result_collector.go:107: === FAIL: =======================[[ERROR]]========================
        🦆 kn service create kn-diag-e2etest --image gcr.io/knative-samples/autoscale-go:0.1
        ┃ Creating service 'kn-diag-e2etest' in namespace 'default':
        ┃ 
        ┃   0.068s The Route is still working to reflect the latest desired specification.
        ┃   0.109s ...
skipped 205 lines unfold_more
        ┃ 
        ┃ 
        ┃ 
        =================================================================
        
--- FAIL: TestKnDiagPlugin (24.36s)
FAIL test/e2e.TestKnDiagPlugin (24.36s)
FAIL test/e2e
```

**Comment by cdlliuy** [comment]
> Seems like your e2e test is still failing...
> 
> ```shell
>  Missing strings: revision, spec.replicas
> uninstalling 'kn' plugin 'kn-diag' from config path '/root/.config/kn'
>     result_collector.go:107: === FAIL: =======================[[ERROR]]========================
>         🦆 kn service create kn-diag-e2etest --image gcr.io/knative-samples/autoscale-go:0.1
>         ┃ Creating service 'kn-diag-e2etest' in namespace 'default':
>         ┃ 
>         ┃   0.068s The Route is still working to reflect the latest desired specification.
>         ┃   0.109s ...
> skipped 205 lines unfold_more
>         ┃ 
>         ┃ 
>         ┃ 
>         =================================================================
>         
> --- FAIL: TestKnDiagPlugin (24.36s)
> FAIL test/e2e.TestKnDiagPlugin (24.36s)
> FAIL test/e2e
> ```
> 
> The error is `"Missing strings: revision, spec.replicas"`

Yes, @maximilien ,   I fixed previous auth provider errors, but the test failed again when I tried to add more detail check on the output.  Working on it now.

**Comment by cdlliuy** [comment]
@maximilien , the e2e failures are resolved now.

**Comment by maximilien** [comment]
yeah. Thanks @cdlliuy 

/approve
/lgtm

**Pull request merged**
