### PR TITLE
fix the panic in table

### PR DESCRIPTION
**Pull request by cdlliuy**
# Changes
- :bug: Fix bug for issue #35 
- :broom: update current implementation for table printing

### CODE REVIEW

**Review by maximilien — COMMENTED** [review]
/ok-to-test
Will try this on my failed service

**Review by maximilien — DISMISSED** [review]
/approve
/lgtm

**Comment by cdlliuy** [comment]
@maximilien ,  can you help to review again after rebase?

**Review by maximilien — APPROVED** [review]
/ok-to-test
/approve
/lgtm

**Comment by maximilien** [comment]
Seems like there was another update to deps. Let's see if this can still merge... Let's monitor jobs

**Pull request merged**
