### PR TITLE
add initial utils

### PR DESCRIPTION
**Pull request by cdlliuy**
push the initial code to get start the project

### CODE REVIEW

**Comment by cdlliuy** [comment]
@maximilien , can you help to review and approve this PR ?  It is used to check in some utils for the further commit .

**Review by maximilien — APPROVED** [review]
Hi, Ying, thanks for moving this forward. Will LGTM but perhaps a couple things to do in future PRs:
1. Why not name all files with _ instead of camel case. Specifically thinking of [connectionCfg.go](https://github.com/knative-sandbox/kn-plugin-diag/pull/12/files#diff-e06e9ddf03f5d8188ab13379946424fb6dadaec1e5742e1f761bf1048ad7d11f) and `printableresource.go`. Consistency in file naming and directory structure make code easier to navigate for all.
2. I see no tests and that makes me sad :( — next update please :)

Cheers 🥂 

/lgtm

**Pull request merged**
