### PR TITLE
add initial code

### PR DESCRIPTION
**Pull request by cdlliuy**
Changes

* This is the inital PR to add an initial cmd framework as the start.
* This is the new PR to pick up the latest changes in test-infrasture

### CODE REVIEW

**Comment by cdlliuy** [comment]
@rhuss  ,the go-coverage check is still in the list even with a new PR.  How can I get rid of it  per https://github.com/knative/test-infra/pull/2611 ?

**Comment by rhuss** [comment]
It might take a bit until the changes are applied. Let's try a retest\

/retest

**Comment by cdlliuy** [comment]
@rhuss ,  can you help to trigger /retest again ...  24 days should be fine to pick the changes up.

**Comment by rhuss** [comment]
@cdlliuy hi :) just back from PTO, sorry for the delay.

/retest

**Comment by cdlliuy** [comment]
@rhuss , sorry for bothering you again, but the `/retest` seems not work. The latest go coverage test is still  in December last year.

**Comment by cdlliuy** [comment]
@rhuss , not sure why, but it seems not retest at all.

https://prow.knative.dev/job-history/gs/knative-prow/pr-logs/directory/pull-knative-sandbox-kn-plugin-diag-go-coverage

**Comment by rhuss** [comment]
ok, let me check tomorrow.

/retest

**Comment by cdlliuy** [comment]
close this to see whether a new PR will help to go through the coverage check

**Pull request closed without merging**
