### PR TITLE
initial PR for readme

### PR DESCRIPTION
**Pull request by cdlliuy**
# Changes

This is the inital PR to add a simple readme as the start. 

/kind documentation

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
/lgtm
/approve

**Comment by cdlliuy** [comment]
@rhuss ,  added the prototype code in the PR. 

I will open issues to track the future updates and refactors that is necessary to the prototype codes.

**Review by rhuss — APPROVED** [review]
lgtm, let's get it merge so that we can continue to work from here on.

/lgtm

**Comment by rhuss** [comment]
@cdlliuy there are various tests failing. Could you please have a look ?

**Comment by cdlliuy** [comment]
@rhuss ,  see issue https://github.com/knative-sandbox/kn-plugin-diag/issues/4,  currently I just submit the prototype code and not developed and add unit test yet.  I guess this is the reason for failure. 

I will take time to get this fixed.

**Comment by cdlliuy** [comment]
@rhuss ,  I can't launch retest. Can you help to add ok-to-test?

**Comment by cdlliuy** [comment]
close this since the prototype code is too big . 

I will create a small PR as initial code, and enhance step by step

**Pull request closed without merging**
